runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies

    - run: pip3 install -r requirements.txt 2>&1
      shell: bash

    - run: python3 -m compileall -q . 2>&1
      shell: bash
    - run: python3 tests.py 2>&1
      shell: bash
    - run: echo "🍏 This job's status is ${{ job.status }}."
      shell: bash

    - name: Build
      run: pyinstaller buildrandomizer.py --onefile --noconsole --name build-engine-randomizer
      shell: bash
    - run: ls -lah dist
      shell: bash

    # make sure we don't need the .app folder, specifically for MacOS
    - run: rm -rf dist/build-engine-randomizer.app
      shell: bash
    - run: ./dist/build-engine-randomizer --version 2>&1
      shell: bash
