name: release
on:
  release:
    types: [published]

jobs:
  Windows-Release:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}

      - run: pip3 install -r requirements.txt

      - run: python3 -m compileall -q .
      - run: python3 tests.py
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Build
        run: pyinstaller buildrandomizer.py --onefile --noconsole --name build-engine-randomizer
      - run: dir dist

      - run: dist/build-engine-randomizer.exe --version

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/build-engine-randomizer.exe
          asset_name: build-engine-randomizer.exe
          asset_content_type: application/octet-stream

  Linux-Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3
      - run: pip3 install -r requirements.txt

      - run: python3 -m compileall -q .
      - run: python3 tests.py
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Build
        run: pyinstaller buildrandomizer.py --onefile --noconsole --name build-engine-randomizer-linux
      - run: ls -lah dist

      - run: dist/build-engine-randomizer-linux --version

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/build-engine-randomizer-linux
          asset_name: build-engine-randomizer-linux
          asset_content_type: application/octet-stream

  MacOS-Release:
    runs-on: macos-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}

      - run: brew install python-tk
      - run: pip3 install -r requirements.txt

      - run: python3 -m compileall -q .
      - run: python3 tests.py
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Build
        run: pyinstaller buildrandomizer.py --onefile --noconsole --name build-engine-randomizer-macos
      - run: ls -lah dist

      - run: rm -rf dist/build-engine-randomizer-macos.app
      - run: dist/build-engine-randomizer-macos --version

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/build-engine-randomizer-macos
          asset_name: build-engine-randomizer-macos
          asset_content_type: application/octet-stream
