name: release
on:
  release:
    types: [published]

jobs:
  Windows-Release:
    runs-on: windows-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}

      - uses: ./.github/run-tests

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/build-engine-randomizer.exe
          asset_name: build-engine-randomizer.exe
          tag: ${{ github.ref }}
          overwrite: true

  Linux-Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3-tk idle3

      - uses: ./.github/run-tests

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/build-engine-randomizer
          asset_name: build-engine-randomizer-linux
          tag: ${{ github.ref }}
          overwrite: true

  MacOS-Release:
    runs-on: macos-latest
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}

      - run: brew install python-tk

      - uses: ./.github/run-tests

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/build-engine-randomizer
          asset_name: build-engine-randomizer-macos
          tag: ${{ github.ref }}
          overwrite: true
